package com.company.security.domain;

import java.io.Serializable;

/**
 * Model class of security_user_idNo.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SecurityUserIdno implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 护照总号码. */
	private String idtotalno;

	/** 用户ID. */
	private Long userId;

	/**
	 * Constructor.
	 */
	public SecurityUserIdno() {
	}

	/**
	 * Set the 护照总号码.
	 * 
	 * @param idtotalno
	 *            护照总号码
	 */
	public void setIdtotalno(String idtotalno) {
		this.idtotalno = idtotalno;
	}

	/**
	 * Get the 护照总号码.
	 * 
	 * @return 护照总号码
	 */
	public String getIdtotalno() {
		return this.idtotalno;
	}

	/**
	 * Set the 用户ID.
	 * 
	 * @param userId
	 *            用户ID
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * Get the 用户ID.
	 * 
	 * @return 用户ID
	 */
	public Long getUserId() {
		return this.userId;
	}


}
