package com.company.security.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of security_user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SecurityUser implements Serializable {

	//正常
	public static final int Status_OK = 0;
	//需要认证
	public static final int Status_needVerified = 1;
	
	//禁用
	public static final int Status_suspend = 2;
	
	
	
	//phone,email,id认证成功
	public static final int verified_Success = 1;
	//认证失败
	public static final int verified_Fail = 0;
	//身份证
	public static final int IDTYPE_IdCard = 0;
	//护照
	public static final int IDTYPE_Passport = 1;
	
	//男
	public static final int SEX_Male=0;
	//女
	public static final int SEX_FeMale=0;
	
	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户ID. */
	private long userId;

	/** 登录的名字. */
	private String loginname;

	/** 姓. */
	private String lastname;

	/** 名. */
	private String firstname;

	/** 显示名字. */
	private String displayname;

	/** 密码. */
	private String password;

	/** 密码扩展字段. */
	private String passwordext;

	/** 邮箱. */
	private String email;

	/** 邮箱认证状态. */
	private int emailverified;

	/** 电话号码. 带国家码的号码，国家码开头是00*/
	private String phone;

	/** 电话号码国家码. */
	private String phoneccode;

	/** 电话号码认证状态. */
	private int phoneverified;

	/** 性别. */
	private int sex;

	/** 生日. */
	private Date birthday;

	/** 头像地址. */
	private String avatar;

	/** 家庭住址. */
	private String homeaddress;

	/** 单位地址. */
	private String businessaddress;

	/** 证件号码. */
	private String idno;

	/** 证件类型. */
	private int idtype;

	/** 证件是否审核过. */
	private int idverified;

	/** 账户状态. */
	private int status;

	/** 拥有的角色. */
	private String roles;

	/** 扩展数据. */
	private String extdate;

	/** 创建时间. */
	private Date createtime;

	/** 创建来源. */
	private String createsource;

	/** 更新时间. */
	private Date updatetime;

	/**
	 * Constructor.
	 */
	public SecurityUser() {
	}

	/**
	 * Set the 用户ID.
	 * 
	 * @param userId
	 *            用户ID
	 */
	public void setUserId(long userId) {
		this.userId = userId;
	}

	/**
	 * Get the 用户ID.
	 * 
	 * @return 用户ID
	 */
	public long getUserId() {
		return this.userId;
	}

	/**
	 * Set the 登录的名字.
	 * 
	 * @param loginname
	 *            登录的名字
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * Get the 登录的名字.
	 * 
	 * @return 登录的名字
	 */
	public String getLoginname() {
		return this.loginname;
	}

	/**
	 * Set the 姓.
	 * 
	 * @param lastname
	 *            姓
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * Get the 姓.
	 * 
	 * @return 姓
	 */
	public String getLastname() {
		return this.lastname;
	}

	/**
	 * Set the 名.
	 * 
	 * @param firstname
	 *            名
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * Get the 名.
	 * 
	 * @return 名
	 */
	public String getFirstname() {
		return this.firstname;
	}

	/**
	 * Set the 显示名字.
	 * 
	 * @param displayname
	 *            显示名字
	 */
	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	/**
	 * Get the 显示名字.
	 * 
	 * @return 显示名字
	 */
	public String getDisplayname() {
		return this.displayname;
	}

	/**
	 * Set the 密码.
	 * 
	 * @param password
	 *            密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密码.
	 * 
	 * @return 密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 密码扩展字段.
	 * 
	 * @param passwordext
	 *            密码扩展字段
	 */
	public void setPasswordext(String passwordext) {
		if(passwordext!=null)
		{
			if(passwordext.length()>8)
			{
				this.passwordext = passwordext.substring(0, 8);
			}
			else
			{
				this.passwordext=passwordext;
			}
		}
		else
		{
			this.passwordext = passwordext;
		}
	}

	/**
	 * Get the 密码扩展字段.
	 * 
	 * @return 密码扩展字段
	 */
	public String getPasswordext() {
		return this.passwordext;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 邮箱认证状态.
	 * 
	 * @param emailverified
	 *            邮箱认证状态
	 */
	public void setEmailverified(int emailverified) {
		this.emailverified = emailverified;
	}

	/**
	 * Get the 邮箱认证状态.
	 * 
	 * @return 邮箱认证状态
	 */
	public int getEmailverified() {
		return this.emailverified;
	}

	/**
	 * Set the 电话号码.
	 * 
	 * @param phone
	 *            电话号码
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the 电话号码.
	 * 
	 * @return 电话号码
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the 电话号码国家码.
	 * 
	 * @param phoneccode
	 *            电话号码国家码
	 */
	public void setPhoneccode(String phoneccode) {
		this.phoneccode = phoneccode;
	}

	/**
	 * Get the 电话号码国家码.
	 * 
	 * @return 电话号码国家码
	 */
	public String getPhoneccode() {
		return this.phoneccode;
	}

	/**
	 * Set the 电话号码认证状态.
	 * 
	 * @param phoneverified
	 *            电话号码认证状态
	 */
	public void setPhoneverified(int phoneverified) {
		this.phoneverified = phoneverified;
	}

	/**
	 * Get the 电话号码认证状态.
	 * 
	 * @return 电话号码认证状态
	 */
	public int getPhoneverified() {
		return this.phoneverified;
	}

	/**
	 * Set the 性别.
	 * 
	 * @param sex
	 *            性别
	 */
	public void setSex(int sex) {
		this.sex = sex;
	}

	/**
	 * Get the 性别.
	 * 
	 * @return 性别
	 */
	public int getSex() {
		return this.sex;
	}

	/**
	 * Set the 生日.
	 * 
	 * @param birthday
	 *            生日
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * Get the 生日.
	 * 
	 * @return 生日
	 */
	public Date getBirthday() {
		return this.birthday;
	}

	/**
	 * Set the 头像地址.
	 * 
	 * @param avatar
	 *            头像地址
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * Get the 头像地址.
	 * 
	 * @return 头像地址
	 */
	public String getAvatar() {
		return this.avatar;
	}

	/**
	 * Set the 家庭住址.
	 * 
	 * @param homeaddress
	 *            家庭住址
	 */
	public void setHomeaddress(String homeaddress) {
		this.homeaddress = homeaddress;
	}

	/**
	 * Get the 家庭住址.
	 * 
	 * @return 家庭住址
	 */
	public String getHomeaddress() {
		return this.homeaddress;
	}

	/**
	 * Set the 单位地址.
	 * 
	 * @param businessaddress
	 *            单位地址
	 */
	public void setBusinessaddress(String businessaddress) {
		this.businessaddress = businessaddress;
	}

	/**
	 * Get the 单位地址.
	 * 
	 * @return 单位地址
	 */
	public String getBusinessaddress() {
		return this.businessaddress;
	}

	/**
	 * Set the 证件号码.
	 * 
	 * @param idno
	 *            证件号码
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * Get the 证件号码.
	 * 
	 * @return 证件号码
	 */
	public String getIdno() {
		return this.idno;
	}

	/**
	 * Set the 证件类型.
	 * 
	 * @param idtype
	 *            证件类型
	 */
	public void setIdtype(int idtype) {
		this.idtype = idtype;
	}

	/**
	 * Get the 证件类型.
	 * 
	 * @return 证件类型
	 */
	public int getIdtype() {
		return this.idtype;
	}

	/**
	 * Set the 证件是否审核过.
	 * 
	 * @param idverified
	 *            证件是否审核过
	 */
	public void setIdverified(int idverified) {
		this.idverified = idverified;
	}

	/**
	 * Get the 证件是否审核过.
	 * 
	 * @return 证件是否审核过
	 */
	public int getIdverified() {
		return this.idverified;
	}

	/**
	 * Set the 账户状态.
	 * 
	 * @param status
	 *            账户状态
	 */
	public void setStatus(int status) {
		this.status = status;
	}

	/**
	 * Get the 账户状态.
	 * 
	 * @return 账户状态
	 */
	public int getStatus() {
		return this.status;
	}

	/**
	 * Set the 拥有的角色.
	 * 
	 * @param roles
	 *            拥有的角色
	 */
	public void setRoles(String roles) {
		this.roles = roles;
	}

	/**
	 * Get the 拥有的角色.
	 * 
	 * @return 拥有的角色
	 */
	public String getRoles() {
		return this.roles;
	}

	/**
	 * Set the 扩展数据.
	 * 
	 * @param extdate
	 *            扩展数据
	 */
	public void setExtdate(String extdate) {
		this.extdate = extdate;
	}

	/**
	 * Get the 扩展数据.
	 * 
	 * @return 扩展数据
	 */
	public String getExtdate() {
		return this.extdate;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 创建来源.
	 * 
	 * @param createsource
	 *            创建来源
	 */
	public void setCreatesource(String createsource) {
		this.createsource = createsource;
	}

	/**
	 * Get the 创建来源.
	 * 
	 * @return 创建来源
	 */
	public String getCreatesource() {
		return this.createsource;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updatetime
	 *            更新时间
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdatetime() {
		return this.updatetime;
	}

	
	public LoginUser getLoginUser()
	{
		LoginUser loginUser = new LoginUser();
		loginUser.setAvatar(this.getAvatar());
		loginUser.setDisplayname(this.getDisplayname());
		loginUser.setEmail(this.getEmail());
		loginUser.setEmailverified(this.getEmailverified());
		loginUser.setLoginname(this.getLoginname());
		loginUser.setPassword(this.getPassword());
		loginUser.setPasswordext(this.getPasswordext());
		loginUser.setPhone(this.getPhone());
		loginUser.setPhoneccode(this.getPhoneccode());
		loginUser.setPhoneverified(this.getPhoneverified());
		loginUser.setRoles(this.getRoles());
		loginUser.setSex(this.getSex());
		loginUser.setStatus(this.getStatus());
		loginUser.setUserId(this.getUserId());
		return loginUser;
	}

	@Override
	public String toString() {
		return "SecurityUser [userId=" + userId + ", loginname=" + loginname + ", lastname=" + lastname + ", firstname="
				+ firstname + ", displayname=" + displayname + ", password=" + password + ", passwordext=" + passwordext
				+ ", email=" + email + ", emailverified=" + emailverified + ", phone=" + phone + ", phoneccode="
				+ phoneccode + ", phoneverified=" + phoneverified + ", sex=" + sex + ", birthday=" + birthday
				+ ", avatar=" + avatar + ", homeaddress=" + homeaddress + ", businessaddress=" + businessaddress
				+ ", idno=" + idno + ", idtype=" + idtype + ", idverified=" + idverified + ", status=" + status
				+ ", roles=" + roles + ", extdate=" + extdate + ", createtime=" + createtime + ", createsource="
				+ createsource + ", updatetime=" + updatetime + "]";
	}
	

}
