package com.company.security.domain;

import java.io.Serializable;

/**
 * Model class of security_user_email.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SecurityUserEmail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 邮箱. */
	private String email;

	/** 用户ID. */
	private long userId;

	/**
	 * Constructor.
	 */
	public SecurityUserEmail() {
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 用户ID.
	 * 
	 * @param userId
	 *            用户ID
	 */
	public void setUserId(long userId) {
		this.userId = userId;
	}

	/**
	 * Get the 用户ID.
	 * 
	 * @return 用户ID
	 */
	public long getUserId() {
		return this.userId;
	}


}
