package com.company.security.domain;

import java.io.Serializable;

/**
 * Model class of 所有的权限.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SecurityAllaction implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 菜单或者按钮ID. */
	private long actionid;

	/** 描述. */
	private String description;

	/** 动作地址. */
	private String action;

	/** 系统. */
	private String system;

	/**
	 * Constructor.
	 */
	public SecurityAllaction() {
	}

	/**
	 * Set the 菜单或者按钮ID.
	 * 
	 * @param actionid
	 *            菜单或者按钮ID
	 */
	public void setActionid(long actionid) {
		this.actionid = actionid;
	}

	/**
	 * Get the 菜单或者按钮ID.
	 * 
	 * @return 菜单或者按钮ID
	 */
	public long getActionid() {
		return this.actionid;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param description
	 *            描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 动作地址.
	 * 
	 * @param action
	 *            动作地址
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * Get the 动作地址.
	 * 
	 * @return 动作地址
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * Set the 系统.
	 * 
	 * @param system
	 *            系统
	 */
	public void setSystem(String system) {
		this.system = system;
	}

	/**
	 * Get the 系统.
	 * 
	 * @return 系统
	 */
	public String getSystem() {
		return this.system;
	}


}
