package com.company.security.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 角色表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SecurityRole implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 角色编号. */
	private long roleid;

	/** 角色名. */
	private String name;

	/** 描述. */
	private String description;

	/** 创建时间. */
	private Date createtime;

	/** 更新时间. */
	private Date updatetime;

	/** 创建来源. */
	private String createsource;

	/**
	 * Constructor.
	 */
	public SecurityRole() {
	}

	/**
	 * Set the 角色编号.
	 * 
	 * @param roleid
	 *            角色编号
	 */
	public void setRoleid(long roleid) {
		this.roleid = roleid;
	}

	/**
	 * Get the 角色编号.
	 * 
	 * @return 角色编号
	 */
	public long getRoleid() {
		return this.roleid;
	}

	/**
	 * Set the 角色名.
	 * 
	 * @param name
	 *            角色名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 角色名.
	 * 
	 * @return 角色名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param description
	 *            描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updatetime
	 *            更新时间
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdatetime() {
		return this.updatetime;
	}

	/**
	 * Set the 创建来源.
	 * 
	 * @param createsource
	 *            创建来源
	 */
	public void setCreatesource(String createsource) {
		this.createsource = createsource;
	}

	/**
	 * Get the 创建来源.
	 * 
	 * @return 创建来源
	 */
	public String getCreatesource() {
		return this.createsource;
	}


}
