package com.company.security.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of security_roleAction.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SecurityRoleaction implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 菜单或者按钮ID. */
	private long actionid;

	/** 角色编号. */
	private long roleid;

	/** 描述. */
	private String description;

	/** 动作地址. */
	private String action;

	/** 权限. */
	private Byte authority;

	/** 创建时间. */
	private Date createtime;

	/** 创建来源. */
	private String createsource;

	/** 更新时间. */
	private Date updatetime;

	/**
	 * Constructor.
	 */
	public SecurityRoleaction() {
	}

	/**
	 * Set the 菜单或者按钮ID.
	 * 
	 * @param actionid
	 *            菜单或者按钮ID
	 */
	public void setActionid(long actionid) {
		this.actionid = actionid;
	}

	/**
	 * Get the 菜单或者按钮ID.
	 * 
	 * @return 菜单或者按钮ID
	 */
	public long getActionid() {
		return this.actionid;
	}

	/**
	 * Set the 角色编号.
	 * 
	 * @param roleid
	 *            角色编号
	 */
	public void setRoleid(long roleid) {
		this.roleid = roleid;
	}

	/**
	 * Get the 角色编号.
	 * 
	 * @return 角色编号
	 */
	public long getRoleid() {
		return this.roleid;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param description
	 *            描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 动作地址.
	 * 
	 * @param action
	 *            动作地址
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * Get the 动作地址.
	 * 
	 * @return 动作地址
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * Set the 权限.
	 * 
	 * @param authority
	 *            权限
	 */
	public void setAuthority(Byte authority) {
		this.authority = authority;
	}

	/**
	 * Get the 权限.
	 * 
	 * @return 权限
	 */
	public Byte getAuthority() {
		return this.authority;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 创建来源.
	 * 
	 * @param createsource
	 *            创建来源
	 */
	public void setCreatesource(String createsource) {
		this.createsource = createsource;
	}

	/**
	 * Get the 创建来源.
	 * 
	 * @return 创建来源
	 */
	public String getCreatesource() {
		return this.createsource;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updatetime
	 *            更新时间
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdatetime() {
		return this.updatetime;
	}


}
